.TH polymnia· 1 2019-jan "linux" "command-line initiation, use, and options"
.na

.SH NAME
polymnia \- ansi-c code analysis, research, and navigation

.SH PATRON
.B polymnia-hymnos
(many praises) muse of divine hymns, dancing, geometry

.SH IMAGERY
tall, beautiful woman wearing a viel and looking toward heaven

.SH SUMMARY
polymnia is a custom code analysis tool offering -- tag navigation for
vim-ide, detailed function complexity analysis, and code-base wide reporting
and research -- for the one-true language (c).

.SH DOCUMENTATION FILES
.nf
.B polymnia (1)·······command-line initiation, use, and options
polymnia (4)       shared devices, files, and configuration
polymnia (7)       decision rationale, objectives, and overview

.SH TABLE OF CONTENTS
.nf  
a) synopsis        command overview
b) general         broad, general information
c) verbosity       options to control feedback
d) system-wide     standard command line overview
e) project data    effecting a single project
f) local           alternate source and destinations
g) reporting       content query and output
h) filtering       cutting reporting volume

.SH A) SYNOPSIS
.B polymnia [OPTIONS]
.nf
  which is the primary production version

.B polymnia_debug [URGENTS] [OPTIONS]
.nf
  which can perform all actions, but with debugging and tracing
  (see yURG for documentation on debugging options)

.SH B) GENERAL
polymnia is a command-line tool with zero real-time interaction.  launch it
with an option, it runs.  that's it.

polymnia only takes one main option per run, i.e., it will update OR report
OR something else.  all the options listed below are main options.

options to configure files, see polymnia (4), can be added to the command line
as well as specific data filtering in section H.

.SH C) VERBOSITY
like most of my applications, there are three levels of feedback optained by
putting a prefix on the primary option.  below is an example for the --register
option...

   ···prefix···  ···option····  ···verbosity····················
   (silent)      --register     only provides a return code
   c (confirm)   --cregister    single line stating result
   v (verbose)   --vregister    details about process and result

.SH C) SYSTEM-WIDE OPTIONS
these options help automate polymnia and turn it into a system-wide code
analysis and research platform.  these commands interact with the central
.B world.txt
file.  see polymnia (4) for more information.

.SS --register
adds the current project directory to the world list.  no duplicates will be
added, so do not worry.

.SS --withdraw <name>
removes the named project directory from the world list.  existing database
information will not be removed.

.SS --normal
updates all projects listed in the world list.  this is quite quick and is
designed to be run either in batch or interactively.

.SS --audit
review security environment and contents of database to see if something
is amiss.

.SS --fix
set-up or remedy security setting or central directory issues.  this is
non-destructive.

.SH D) PROJECT DATA OPTIONS
the central database can also perform a few operations on individual projects
in order to keep the database clean.

.SS --verify
checks the current project's location, structure, and data to verify suitability
for inclusion.  does not effect main registry or database.

.SS --update
appends the database with new data from current code project.  if the project
already exists, it is updated.  if not, it is added.

.SS --install
does a combination of --register and --update so that both the registry and
database are updated immediately.

.SS --clear
remove data for the current project data from database.  but, the project
is not removed from the registry.

.SS --remove
does a combination of --withdraw and --clear so that both the registry and
database are updated immediately.

.SH E) LOCAL OPTIONS
to aide analysis, limited or full databases, world files, or external function
lists can be useful.  polymnia does not care.  these options are helpers and
do not allow for 'c' (confirm) or 'v' (verbose) options.

.SS --local
orders polymnia to use the database polymnia_local.db in the current directory
as source and destination for data.

.SS --database <name>
orders polymnia to use an alternate database as source and destination for
all the options above.

.SS --world <name>
orders polymnia to use an alternate world file as source and destination for
all the options above.

.SS --external <name>
orders polymnia to use an alternate external function file as source for all
the options above.

.SH F) REPORTING OPTIONS
polymnia supports several overviews of database content that provide all
information stored, typically for use in a spreadsheet.

.SS --htags
refresh data and write detailed tags format specifically designed to support
my vim-macros and vim-ide.  no database, uses local data.

.SS --stats
present database and system-wide statistics contained within for auditing
and quick access.

.SS --tree
generates a hyleoroi dump of all function interactions for a convergence graph.

.SS --fulltree
just like --tree, except data for all ylibs and every other external call
is included.

.SS --report <name>
like most of my applications, there are three levels of report formatting
available by putting a prefix on the report name.  below is an example for the
"projects" report...

   ···prefix···  ···option····  ···verbosity····················
   d (dump)      dprojects      single line per record, no formatting
   f (format)    fprojects      adds titles and spacing
   (silent)      projects       full format with export-import hints

.nf
projects        full project inventory
files           file inventory for a project
ylibs           ylib inventory for a project
used            system-wide calls to a specific ylib function
externs         external inventory

.B --treeview
.RS 8
write heirarchical, intented view for visualization programs
.RE

.SH G) FILTERING OPTIONS
polymnia supports a series of filters to help reduce the volume and
target specific settings in certain statistics.

.B --project <name>
.RS 8
limit output to only a specific project
.RE

.B --debug
.RS 8
show suspected issues identified in debugging
.RE

.B --linux
.RS 8
show all tags with process, system, or filesystem use
.RE

.B --data
.RS 8
show all tags with file reading or writing
.RE

.SH FILES
polymnia stores files in two places -- local files in the code directories and
a common directory in /var/lib.

.B polymnia.db
is the shared database with all code analysis stored in /var/lib/polymnia/.

.B external.txt
is a list of categorized external functions stored in /var/lib/polymnia/.

.B polymnia.mystry
local file with list of all unknown external calls including file, line,
and source function.

.SH HERITAGE
polymnia-hymnos (many praises) is the muse of divine hymns, the lyre, dancing,
geometry, and grammar.  the muses (mousai) are nine daughters of zeus and
mnemosyne (titan of memory) and are the goddesses of art, literature, and
science who inspire creation and enthusiasm.  polymnia is usually depicted
wearing a veil and looking up to the heavens.

.SH AUTHOR
jelloshrike at gmail dot com

.SH COLOPHON
this page is part of a documentation package meant to make use of the
heatherly tools easier and faster.
